eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082
spring:
  application:
    name: post-comment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: frame
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  cloud:
    config:
      name: blog-configuration-service
      uri:
      - http://localhost:8099
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
